# Generated by Django 3.1 on 2021-03-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_1', models.CharField(max_length=40)),
                ('data_2', models.CharField(max_length=40)),
            ],
        ),
    ]
