# Generated by Django 3.2 on 2021-04-22 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DSS_App', '0002_auto_20210422_1519'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('t_id', models.AutoField(primary_key=True, serialize=False)),
                ('sender_acc', models.IntegerField(unique=True)),
                ('receiver_acc', models.IntegerField(unique=True)),
                ('transactions_amount', models.FloatField()),
                ('transaction_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
